### PR TITLE
ADDED RequestID feature

### PR DESCRIPTION
**Pull request by losingle**

### CODE REVIEW

**Comment by savsgio** [comment]
Hi @losingle,

You could do that with a middleware. it's not necessary to add inside the internal handler, because it's your custom functionality. Just copy it and register the middleware in your atreugo instance.

**Comment by losingle** [comment]
I think this RequestID is fundamental, 
because even the simplest business needs to be monitored, 
but monitoring is not possible without RequestID

**Comment by losingle** [comment]
But the best way to do that, really is to use middleware

**Comment by losingle** [comment]
@savsgio 
Middleware we made a change to atreugo Middleware, dividing it into beforeMiddlewares and afterMiddlewares, as they execute before and after viewFn
Atreugo is considering offering Middlewares as well?

**Comment by savsgio** [comment]
Yeah atreguo offer middlewares https://godoc.org/github.com/savsgio/atreugo#Atreugo.UseMiddleware

**Comment by savsgio** [comment]
But the middlewares will just execute before `vienFn` is executed.

**Comment by savsgio** [comment]
You could make a PR to adds support to Before/After Middlewares :)

**Comment by savsgio** [comment]
About `RequestID` middleware, it would be a good idea to create a `middlewares` folder and adds inside it.

**Comment by losingle** [comment]
well,I modified it in this way

**Comment by savsgio** [comment]
Make two PR, please!

**Comment by losingle** [comment]
If middleware is used to append RequestID without changing the atreugo structure, obtaining RequestID externally is inconvenient.
I wanted to get RequestID through atreugo.requestctx

**Comment by savsgio** [comment]
No because, the RequestID is a header, it's not necessary add to RequestCtx structure to access to it.

**Comment by losingle** [comment]
Okay, so just provide the entry that the header gets

**Comment by savsgio** [comment]
One way is adds a method that return the RequestID if it's present in request without change structure

For example

```func (ctx *RequestCtx) RequestID() []bytes{
   return ctx.Request.Headers.Peek("X-Request-ID")
}```

**Comment by losingle** [comment]
I felt I had to use RequestID as a basic feature, so I didn't submit the middleware PR over time

**Comment by savsgio** [comment]
I don't understand you, sorry.

What do you mean?

**Comment by losingle** [comment]
I think the current PR should be ok

**Comment by savsgio** [comment]
Sorry, but the RequestID function could be a middleware function perfectly.

**Comment by savsgio** [comment]
I've just added the before/after middlewares.

**Comment by losingle** [comment]
> Sorry, but the RequestID function could be a middleware function perfectly.
> 
> The middlewares add granularity to the handler and extensibility if you need

This conclusion is correct, but I still feel that RequestID should be provided as a basic feature
as atreugo grows, many of features depend on requestID

**Comment by savsgio** [comment]
Yeah it's a basic feature, so i will added into predefined middlewares to use if it's neccesary or not. Also adds the method into `atreugo.RequestCtx` to get their value easier.

**Comment by savsgio** [comment]
If you want to make this chage, i will accept your PR

**Comment by losingle** [comment]
thanks

**Comment by savsgio** [comment]
I've just added the request id middleware into the middlewares folder

**Comment by savsgio** [comment]
Now, if you register that middleware, you could access to de header value with `ctx.RequestID()`

**Comment by losingle** [comment]
Sorry, I'm not familiar with fasthttp server. I recently discovered that the server API has an [ID](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.ID) method that is actually RequestID

**Pull request closed without merging**
